export const awardConstants = {
    CREATE_AWARD_REQUEST: "CREATE_AWARD_REQUEST",
    CREATE_AWARD_SUCCESS: "CREATE_AWARD_SUCCESS",
    CREATE_AWARD_FAILURE: "CREATE_AWARD_FAILURE",

    GET_ALL_AWARDS_REQUEST: "GET_ALL_AWARDS_REQUEST",
    GET_ALL_AWARDS_SUCCESS: "GET_ALL_AWARDS_SUCCESS",
    GET_ALL_AWARDS_FAILURE: "GET_ALL_AWARDS_FAILURE",

    GET_AWARD_REQUEST: "GET_AWARD_REQUEST",
    GET_AWARD_SUCCESS: "GET_AWARD_SUCCESS",
    GET_AWARD_FAILURE: "GET_AWARD_FAILURE",

    DELETE_AWARD_REQUEST: "DELETE_AWARD_REQUEST",
    DELETE_AWARD_SUCCESS: "DELETE_AWARD_SUCCESS",
    DELETE_AWARD_FAILURE: "DELETE_AWARD_FAILURE",

    UPDATE_AWARD_REQUEST: "UPDATE_AWARD_REQUEST",
    UPDATE_AWARD_SUCCESS: "UPDATE_AWARD_SUCCESS",
    UPDATE_AWARD_FAILURE: "UPDATE_AWARD_FAILURE"
}