export const departmentConstants = {
    CREATE_DEPARTMENT_REQUEST: "CREATE_DEPARTMENT_REQUEST",
    CREATE_DEPARTMENT_SUCCESS: "CREATE_DEPARTMENT_SUCCESS",
    CREATE_DEPARTMENT_FAILURE: "CREATE_DEPARTMENT_FAILURE",

    UPDATE_DEPARTMENT_REQUEST: "UPDATE_DEPARTMENT_REQUEST",
    UPDATE_DEPARTMENT_SUCCESS: "UPDATE_DEPARTMENT_SUCCESS",
    UPDATE_DEPARTMENT_FAILURE: "UPDATE_DEPARTMENT_FAILURE",

    DELETE_DEPARTMENT_REQUEST: "DELETE_DEPARTMENT_REQUEST",
    DELETE_DEPARTMENT_SUCCESS: "DELETE_DEPARTMENT_SUCCESS",
    DELETE_DEPARTMENT_FAILURE: "DELETE_DEPARTMENT_FAILURE",

    DELETE_CHILD_DEPARTMENT_REQUEST: "DELETE_CHILD_DEPARTMENT_REQUEST",
    DELETE_CHILD_DEPARTMENT_SUCCESS: "DELETE_CHILD_DEPARTMENT_SUCCESS",
    DELETE_CHILD_DEPARTMENT_FAILURE: "DELETE_CHILD_DEPARTMENT_FAILURE",

    GET_ALL_DEPARTMENTS_REQUEST: "GET_ALL_DEPARTMENTS_REQUEST",
    GET_ALL_DEPARTMENTS_SUCCESS: "GET_ALL_DEPARTMENTS_SUCCESS",
    GET_ALL_DEPARTMENTS_FAILURE: "GET_ALL_DEPARTMENTS_FAILURE",

    GET_DEPARTMENT_REQUEST: "GET_DEPARTMENT_REQUEST",
    GET_DEPARTMENT_SUCCESS: "GET_DEPARTMENT_SUCCESS",
    GET_DEPARTMENT_FAILURE: "GET_DEPARTMENT_FAILURE",

    GET_CHILD_DEPARTMENTS_SUCCESS: "GET_CHILD_DEPARTMENTS_SUCCESS",
    GET_CHILD_DEPARTMENTS_REQUEST: "GET_CHILD_DEPARTMENTS_REQUEST",
    GET_CHILD_DEPARTMENTS_FAILURE: "GET_CHILD_DEPARTMENTS_FAILURE",

    GET_PARENT_DEPARTMENTS_REQUEST: "GET_PARENT_DEPARTMENTS_REQUEST",
    GET_PARENT_DEPARTMENTS_SUCCESS: "GET_PARENT_DEPARTMENTS_SUCCESS",
    GET_PARENT_DEPARTMENTS_FAILURE: "GET_PARENT_DEPARTMENTS_FAILURE",

    CLEAR_CHILD_DEPARTMENTS: "CLEAR_CHILD_DEPARTMENTS",

    UPDATE_DEPARTMENT_FIELD: "UPDATE_DEPARTMENT_FIELD"
};