export const employeeConstants = {
    CREATE_EMPLOYEE_REQUEST: "CREATE_EMPLOYEE_REQUEST",
    CREATE_EMPLOYEE_SUCCESS: "CREATE_EMPLOYEE_SUCCESS",
    CREATE_EMPLOYEE_FAILURE: "CREATE_EMPLOYEE_FAILURE",

    GET_ALL_EMPLOYEES_REQUEST: "GET_ALL_EMPLOYEE_REQUEST",
    GET_ALL_EMPLOYEES_SUCCESS: "GET_ALL_EMPLOYEE_SUCCESS",
    GET_ALL_EMPLOYEES_FAILURE: "GET_ALL_EMPLOYEE_FAILURE",

    GET_EMPLOYEE_REQUEST: "GET_EMPLOYEE_REQUEST",
    GET_EMPLOYEE_SUCCESS: "GET_EMPLOYEE_SUCCESS",
    GET_EMPLOYEE_FAILURE: "GET_EMPLOYEE_FAILURE",

    GET_EMPLOYEE_PROFILE_REQUEST: "GET_EMPLOYEE_PROFILE_REQUEST",
    GET_EMPLOYEE_PROFILE_SUCCESS: "GET_EMPLOYEE_PROFILE_SUCCESS",
    GET_EMPLOYEE_PROFILE_FAILURE: "GET_EMPLOYEE_PROFILE_FAILURE",

    DELETE_EMPLOYEE_REQUEST: "DELETE_EMPLOYEE_REQUEST",
    DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
    DELETE_EMPLOYEE_FAILURE: "DELETE_EMPLOYEE_FAILURE",

    UPDATE_EMPLOYEE_REQUEST: "UPDATE_EMPLOYEE_REQUEST",
    UPDATE_EMPLOYEE_SUCCESS: "UPDATE_EMPLOYEE_SUCCESS",
    UPDATE_EMPLOYEE_FAILURE: "UPDATE_EMPLOYEE_FAILURE",

    UPDATE_EMPLOYEE_PHOTO_REQUEST: "UPDATE_EMPLOYEE_PHOTO_REQUEST",
    UPDATE_EMPLOYEE_PHOTO_SUCCESS: "UPDATE_EMPLOYEE_PHOTO_SUCCESS",
    UPDATE_EMPLOYEE_PHOTO_FAILURE: "UPDATE_EMPLOYEE_PHOTO_FAILURE",

    DELETE_EMPLOYEE_PHOTO_REQUEST: "DELETE_EMPLOYEE_PHOTO_REQUEST",
    DELETE_EMPLOYEE_PHOTO_SUCCESS: "DELETE_EMPLOYEE_PHOTO_SUCCESS",
    DELETE_EMPLOYEE_PHOTO_FAILURE: "DELETE_EMPLOYEE_PHOTO_FAILURE",

    UPDATE_EMPLOYEE_FIELD: "UPDATE_EMPLOYEE_FIELD"
};